# Generated by Django 3.2.17 on 2023-03-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=255)),
                ('meta', models.TextField(default='')),
                ('input', models.TextField()),
                ('output', models.TextField(default='')),
                ('duration', models.FloatField()),
                ('error', models.TextField(default='')),
                ('feedback_yn', models.BooleanField(null=True)),
                ('feedback_details', models.TextField(default=None)),
            ],
        ),
    ]
