# Generated by Django 3.2.18 on 2023-04-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0004_auto_20230410_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequestlog',
            name='duration',
            field=models.FloatField(null=True),
        ),
    ]
