# Generated by Django 4.2.11 on 2024-04-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0010_remove_apirequestlog_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequestlog',
            name='feedback_details',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='apirequestlog',
            name='feedback_thumb',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
    ]
