# Generated by Django 3.2.17 on 2023-03-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequestlog',
            name='feedback_details',
            field=models.TextField(default=''),
        ),
    ]
