# Generated by Django 3.2.18 on 2023-04-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_alter_apirequestlog_feedback_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apirequestlog',
            old_name='meta',
            new_name='meta_url',
        ),
        migrations.RemoveField(
            model_name='apirequestlog',
            name='feedback_yn',
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='feedback_thumb',
            field=models.CharField(default='', max_length=1, null=True),
        ),
    ]
