# Generated by Django 4.2.11 on 2024-04-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0006_alter_apirequestlog_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apirequestlog',
            name='from_cache',
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='model_params',
            field=models.TextField(default=''),
        ),
    ]
