# Generated by Django 4.2.11 on 2024-04-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0007_remove_apirequestlog_from_cache_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apirequestlog',
            old_name='meta_url',
            new_name='meta_data',
        ),
        migrations.RemoveField(
            model_name='apirequestlog',
            name='browser_id',
        ),
    ]
